// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK2KqBx_WW8mgsCaZzHCJivoxDpf_DesM',
    appId: '1:906279944668:web:ae8b107b1d60efafc18f19',
    messagingSenderId: '906279944668',
    projectId: 'emergify-app-f2bb4',
    authDomain: 'emergify-app-f2bb4.firebaseapp.com',
    storageBucket: 'emergify-app-f2bb4.appspot.com',
    measurementId: 'G-K393SQCTQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAACpCtZ8fmbuFiE5wOP2HESnCZ7AfgQ5s',
    appId: '1:906279944668:android:6e2e6bbb511c836cc18f19',
    messagingSenderId: '906279944668',
    projectId: 'emergify-app-f2bb4',
    storageBucket: 'emergify-app-f2bb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNBoKUap4uAIp3x5S4oXFBCVN_PHTW1aw',
    appId: '1:906279944668:ios:3e5c0cb00b0368d4c18f19',
    messagingSenderId: '906279944668',
    projectId: 'emergify-app-f2bb4',
    storageBucket: 'emergify-app-f2bb4.appspot.com',
    iosBundleId: 'com.example.emerfigy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNBoKUap4uAIp3x5S4oXFBCVN_PHTW1aw',
    appId: '1:906279944668:ios:3e5c0cb00b0368d4c18f19',
    messagingSenderId: '906279944668',
    projectId: 'emergify-app-f2bb4',
    storageBucket: 'emergify-app-f2bb4.appspot.com',
    iosBundleId: 'com.example.emerfigy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK2KqBx_WW8mgsCaZzHCJivoxDpf_DesM',
    appId: '1:906279944668:web:e1baf5336eb01765c18f19',
    messagingSenderId: '906279944668',
    projectId: 'emergify-app-f2bb4',
    authDomain: 'emergify-app-f2bb4.firebaseapp.com',
    storageBucket: 'emergify-app-f2bb4.appspot.com',
    measurementId: 'G-E0KZ774LL6',
  );
}
